### ISSUE TITLE
Rem Tree.css and Modern Table Row  conflict.

### ISSUE THREAD

**Issue by kyle-one** [browneyedsoul/RemNote-CSS-Library#7]
True:
![image](https://user-images.githubusercontent.com/44631434/179651906-9a9bec5e-40a9-4806-a19b-99e964212c5c.png)

False:
![image](https://user-images.githubusercontent.com/44631434/179651852-52068543-16fe-40af-9869-7b769571f603.png)

**Comment by browneyedsoul** [comment]
Got it. Thanks for reporting! I already noticed the issue and have my mind to deal with disabling the tree in a local node. But I can't say when it will be done, but definitely it is on the roadmap. Stay tuned!

**Comment by kyle-one** [comment]
Rem Tree.css and Kanban.css conflict
![image](https://user-images.githubusercontent.com/44631434/179653065-4baff9af-cc4a-4b6d-bfcc-9f516680e339.png)

**Comment by kyle-one** [comment]
> Got it. Thanks for reporting! I already noticed the issue and have my mind to deal with disabling the tree in a local node. But I can't say when it will be done, but definitely it is on the roadmap. Stay tuned!

okkkkkkk, thanks~

**Comment by browneyedsoul** [comment]
![220729-220150](https://user-images.githubusercontent.com/56161102/181766047-a912cd85-99bd-499f-b3ce-00d70518b639.png)

How about this one?

```css
[data-rem-container-tags~="fixer"] {
  display: flex;
  flex-direction: column;
}
[data-rem-container-tags~="fixer"] .tree-node--parent::before,
[data-rem-container-tags~="fixer"] .tree-node--children::before,
[data-rem-container-tags~="fixer"] .tree-node--children::after {
  display: none;
}
[data-rem-container-tags~="fixer"] .tree-node--children {
  border-left: unset !important;
}
[data-rem-container-tags~="fixer"] .animate-zoom-into-bullet > .tree-node--children {
  width: 100% !important;
}
```
